name: Hello world!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: print hello world
        run: |
          echo "Hello world!"
      - name: Now it is
        run: |
          echo date
      - name: Directory content
        run: |
          echo ls